[http_server]
insecure_http = true

[attestation_token]
insecure_api = true

[attestation_service]
type = "coco_as_builtin"
work_dir = "/opt/confidential-containers/attestation-service"
policy_engine = "opa"

[attestation_service.attestation_token_broker]
type = "Ear"
duration_min = 5

[attestation_service.rvps_config]
type = "BuiltIn"
store_type = "LocalFs"

[policy_engine]
policy_path = "/opa/confidential-containers/kbs/policy.rego"

[admin]
insecure_api = true

[[plugins]]
name = "resource"
type = "LocalFs"
dir_path = "/opt/confidential-containers/kbs/repository"

[[plugins]]
name = "splitapi"
type = "CertManager"
plugin_dir = "/opt/confidential-containers/kbs/plugin/splitapi"